package py.com.aseguradoratajy.tajydemo.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import py.com.aseguradoratajy.tajydemo.entities.Products;
import py.com.aseguradoratajy.tajydemo.entities.Insurance;

import py.com.aseguradoratajy.tajydemo.entities.ProductsDao;
import py.com.aseguradoratajy.tajydemo.entities.InsuranceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productsDaoConfig;
    private final DaoConfig insuranceDaoConfig;

    private final ProductsDao productsDao;
    private final InsuranceDao insuranceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        insuranceDaoConfig = daoConfigMap.get(InsuranceDao.class).clone();
        insuranceDaoConfig.initIdentityScope(type);

        productsDao = new ProductsDao(productsDaoConfig, this);
        insuranceDao = new InsuranceDao(insuranceDaoConfig, this);

        registerDao(Products.class, productsDao);
        registerDao(Insurance.class, insuranceDao);
    }
    
    public void clear() {
        productsDaoConfig.clearIdentityScope();
        insuranceDaoConfig.clearIdentityScope();
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

    public InsuranceDao getInsuranceDao() {
        return insuranceDao;
    }

}
