package py.com.aseguradoratajy.tajydemo.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INSURANCE".
 */
@Entity
public class Insurance {

    @Id
    private Long id;
    private String identifyCard;
    private Integer sectionCode;
    private String sectionDescription;
    private String policy;
    private String endorsement;
    private String feeDetail;
    private String ruc;
    private String insurance;
    private String comercialPhone;
    private String comercialAddress;
    private String parcitularAddress;
    private String dateFrom;
    private String dateTo;
    private String issue;
    private String expiration;
    private String amount;
    private String payment;
    private String balance;
    private String lastPayment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Insurance() {
    }

    public Insurance(Long id) {
        this.id = id;
    }

    @Generated
    public Insurance(Long id, String identifyCard, Integer sectionCode, String sectionDescription, String policy, String endorsement, String feeDetail, String ruc, String insurance, String comercialPhone, String comercialAddress, String parcitularAddress, String dateFrom, String dateTo, String issue, String expiration, String amount, String payment, String balance, String lastPayment) {
        this.id = id;
        this.identifyCard = identifyCard;
        this.sectionCode = sectionCode;
        this.sectionDescription = sectionDescription;
        this.policy = policy;
        this.endorsement = endorsement;
        this.feeDetail = feeDetail;
        this.ruc = ruc;
        this.insurance = insurance;
        this.comercialPhone = comercialPhone;
        this.comercialAddress = comercialAddress;
        this.parcitularAddress = parcitularAddress;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.issue = issue;
        this.expiration = expiration;
        this.amount = amount;
        this.payment = payment;
        this.balance = balance;
        this.lastPayment = lastPayment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifyCard() {
        return identifyCard;
    }

    public void setIdentifyCard(String identifyCard) {
        this.identifyCard = identifyCard;
    }

    public Integer getSectionCode() {
        return sectionCode;
    }

    public void setSectionCode(Integer sectionCode) {
        this.sectionCode = sectionCode;
    }

    public String getSectionDescription() {
        return sectionDescription;
    }

    public void setSectionDescription(String sectionDescription) {
        this.sectionDescription = sectionDescription;
    }

    public String getPolicy() {
        return policy;
    }

    public void setPolicy(String policy) {
        this.policy = policy;
    }

    public String getEndorsement() {
        return endorsement;
    }

    public void setEndorsement(String endorsement) {
        this.endorsement = endorsement;
    }

    public String getFeeDetail() {
        return feeDetail;
    }

    public void setFeeDetail(String feeDetail) {
        this.feeDetail = feeDetail;
    }

    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public String getInsurance() {
        return insurance;
    }

    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    public String getComercialPhone() {
        return comercialPhone;
    }

    public void setComercialPhone(String comercialPhone) {
        this.comercialPhone = comercialPhone;
    }

    public String getComercialAddress() {
        return comercialAddress;
    }

    public void setComercialAddress(String comercialAddress) {
        this.comercialAddress = comercialAddress;
    }

    public String getParcitularAddress() {
        return parcitularAddress;
    }

    public void setParcitularAddress(String parcitularAddress) {
        this.parcitularAddress = parcitularAddress;
    }

    public String getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(String dateFrom) {
        this.dateFrom = dateFrom;
    }

    public String getDateTo() {
        return dateTo;
    }

    public void setDateTo(String dateTo) {
        this.dateTo = dateTo;
    }

    public String getIssue() {
        return issue;
    }

    public void setIssue(String issue) {
        this.issue = issue;
    }

    public String getExpiration() {
        return expiration;
    }

    public void setExpiration(String expiration) {
        this.expiration = expiration;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getPayment() {
        return payment;
    }

    public void setPayment(String payment) {
        this.payment = payment;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public String getLastPayment() {
        return lastPayment;
    }

    public void setLastPayment(String lastPayment) {
        this.lastPayment = lastPayment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public String toString() {
        return "Insurance{" +
                "id=" + id +
                ", identifyCard='" + identifyCard + '\'' +
                ", sectionCode=" + sectionCode +
                ", sectionDescription='" + sectionDescription + '\'' +
                ", policy='" + policy + '\'' +
                ", endorsement='" + endorsement + '\'' +
                ", feeDetail='" + feeDetail + '\'' +
                ", ruc='" + ruc + '\'' +
                ", insurance='" + insurance + '\'' +
                ", comercialPhone='" + comercialPhone + '\'' +
                ", comercialAddress='" + comercialAddress + '\'' +
                ", parcitularAddress='" + parcitularAddress + '\'' +
                ", dateFrom='" + dateFrom + '\'' +
                ", dateTo='" + dateTo + '\'' +
                ", issue='" + issue + '\'' +
                ", expiration='" + expiration + '\'' +
                ", amount='" + amount + '\'' +
                ", payment='" + payment + '\'' +
                ", balance='" + balance + '\'' +
                ", lastPayment='" + lastPayment + '\'' +
                '}';
    }
}
