package py.com.aseguradoratajy.tajydemo.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MARKS".
 */
@Entity
public class Marks {

    @Id
    private Long id;
    private Integer brandCode;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Marks() {
    }

    public Marks(Long id) {
        this.id = id;
    }

    @Generated
    public Marks(Long id, Integer brandCode, String description) {
        this.id = id;
        this.brandCode = brandCode;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBrandCode() {
        return brandCode;
    }

    public void setBrandCode(Integer brandCode) {
        this.brandCode = brandCode;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
