package py.com.aseguradoratajy.tajydemo.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUCTS".
 */
@Entity
public class Products {

    @Id
    private Long id;
    private Integer productId;
    private String productDescription;
    private String productDetails;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Products() {
    }

    public Products(Long id) {
        this.id = id;
    }

    @Generated
    public Products(Long id, Integer productId, String productDescription, String productDetails) {
        this.id = id;
        this.productId = productId;
        this.productDescription = productDescription;
        this.productDetails = productDetails;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getProductDescription() {
        return productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public String getProductDetails() {
        return productDetails;
    }

    public void setProductDetails(String productDetails) {
        this.productDetails = productDetails;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
