package py.com.aseguradoratajy.tajydemo.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCTS".
*/
public class ProductsDao extends AbstractDao<Products, Long> {

    public static final String TABLENAME = "PRODUCTS";

    /**
     * Properties of entity Products.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ProductId = new Property(1, Integer.class, "productId", false, "PRODUCT_ID");
        public final static Property ProductDescription = new Property(2, String.class, "productDescription", false, "PRODUCT_DESCRIPTION");
        public final static Property ProductDetails = new Property(3, String.class, "productDetails", false, "PRODUCT_DETAILS");
    }


    public ProductsDao(DaoConfig config) {
        super(config);
    }
    
    public ProductsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PRODUCT_ID\" INTEGER," + // 1: productId
                "\"PRODUCT_DESCRIPTION\" TEXT," + // 2: productDescription
                "\"PRODUCT_DETAILS\" TEXT);"); // 3: productDetails
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Products entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(2, productId);
        }
 
        String productDescription = entity.getProductDescription();
        if (productDescription != null) {
            stmt.bindString(3, productDescription);
        }
 
        String productDetails = entity.getProductDetails();
        if (productDetails != null) {
            stmt.bindString(4, productDetails);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Products entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(2, productId);
        }
 
        String productDescription = entity.getProductDescription();
        if (productDescription != null) {
            stmt.bindString(3, productDescription);
        }
 
        String productDetails = entity.getProductDetails();
        if (productDetails != null) {
            stmt.bindString(4, productDetails);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Products readEntity(Cursor cursor, int offset) {
        Products entity = new Products( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // productId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // productDescription
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // productDetails
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Products entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setProductDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProductDetails(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Products entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Products entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Products entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
